# Generated by Django 4.1.6 on 2023-03-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_loyalty_customer_localty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='localty',
            new_name='locality',
        ),
    ]
